# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 04:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('rate', models.IntegerField(blank=True, max_length=30)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('address', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Organization'),
        ),
        migrations.AddField(
            model_name='challan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Client'),
        ),
        migrations.AddField(
            model_name='challan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Organization'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Organization'),
        ),
    ]
