# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
    ]
