# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20170923_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='bill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Bill'),
        ),
    ]
