# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20170923_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
