# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20170924_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='organization',
            name='pan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='challan',
            name='job',
            field=models.TextField(max_length=128),
        ),
    ]
