# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20170927_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
    ]
