# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 11:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20170929_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=128)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cgst_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('sgst_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('igst_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='cgst_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='igst_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sgst_rate',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='job',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='challan',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Challan'),
        ),
    ]
