# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20171015_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_details',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
