# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_organization_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='rate',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
